apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hello
  namespace: go-hello
spec:
  selector:
    matchLabels:
      app: go-hello
  template:
    metadata:
      labels:
        app: go-hello
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: go-hello
          imagePullPolicy: Always
          image: myapp
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
              name: http
