kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

images:
- name: myapp
  newName: kdwilson/go-hello
  newTag: 8a307dac2fe3c27df30f087dffc45b6623f46dd3

resources:
- deployment.yaml
- service.yaml
