kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

images:
- name: myapp
  newName: kdwilson/go-hello
  newTag: 4d88f166fd46cde38896a26bd18b9dcfea3b6da2

resources:
- deployment.yaml
- service.yaml
