name: CD
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Tailscale
        uses: tailscale/github-action@ecdb6a2aed7b74d1c8ec0c78fbd76a84b9809b28
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - name: set up kustomize
        uses: imranismail/setup-kustomize@v1
      - run: |
          kustomize build local -o kubernetes.yaml
      - name: kubectl apply
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f kubernetes.yaml
